services:
  portfolio-api:
    build: .
    container_name: portfolio-api
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      QUARKUS_PROFILE: prod
    networks:
      - homelab

networks:
  homelab:
    external: true