quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  hibernate-orm:
    log:
      sql: true
    format-sql: true
    schema-management:
      strategy: validate
    database:
      generation: validate

  flyway:
    migrate-at-start: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair-at-start: true

  http:
    port: 8080