ALTER TABLE profile
    ADD COLUMN IF NOT EXISTS bio       TEXT,
    ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255),
    ADD COLUMN IF NOT EXISTS job_title VARCHAR(100),
    ADD COLUMN IF NOT EXISTS location  VARCHAR(100);